### ISSUE TITLE
Can you consider integrate flutter_native_splash?

### ISSUE THREAD

**Issue by trietbui85** [salvadordeveloper/flutter-crypto-app#1]
Thanks for nice app. It's hard to find a good repo to learn Flutter with Riverpod like yours.

I see this app doesn't have any splash yet. Can you consider integrate https://pub.dev/packages/flutter_native_splash?

**Comment by salvadordeveloper** [comment]
Thanks for the recommendation @anticafe, I implemented this plugin in the last commit.
