### ISSUE TITLE
Error: A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.  - 

### ISSUE THREAD

**Issue by RajuNarula369** [salvadordeveloper/flutter-crypto-app#11]
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/settings_ui-1.0.0/lib/src/cupertino_settings_item.dart:76:51: Error: A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.
 - 'ListTileThemeData' is from 'package:flutter/src/material/list_tile.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/material/list_tile.dart').
 - 'ListTileTheme' is from 'package:flutter/src/material/list_tile.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/material/list_tile.dart').
    final ListTileTheme tileTheme = ListTileTheme.of(context);
                                                  ^

**Comment by salvadordeveloper** [comment]
Fixed. The package settings_ui needed to be updated.
