### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by taoaiyi1108** [salvadordeveloper/flutter-crypto-app#4]
![image](https://user-images.githubusercontent.com/29810247/123245280-41cf4980-d517-11eb-8a10-86a9918eff35.png)
No file or variants found for asset: .env.

**Comment by salvadordeveloper** [comment]
Please check the README. 

You should rename **.env.example** to **.env**. Then create an account in [Cryptowatch](https://cryptowat.ch/) to get an API Key and add it to your .env file.
